# JWT 설정  
jwt:
  secret-key: ddobang-super-secret-key-for-development-only-change-in-production
  access-token-expiry: 900000      # 15분 (밀리초)
  refresh-token-expiry: 604800000  # 7일 (밀리초)
  signup-token-expiry: 1800000     # 30분 (밀리초)

# 데이터베이스 설정 (Docker 환경에서는 사용하지 않음)
mysql:
  username: ddobang
  password: password

# OAuth2 설정 (기본값 - 실제 키로 변경 필요)
oauth:
  kakao:
    client-id: YOUR_KAKAO_CLIENT_ID_CHANGE_ME
    client-secret: YOUR_KAKAO_CLIENT_SECRET_CHANGE_ME

# AWS S3 설정 (선택적)
aws:
  s3:
    access-key: YOUR_AWS_ACCESS_KEY_OPTIONAL
    secret-key: YOUR_AWS_SECRET_KEY_OPTIONAL
    bucket: ddobang-uploads
    region: ap-northeast-2
