server:
  port: 8080

spring:
  application:
    name: backend

  profiles:
    # 기본 활성 프로파일은 h2로 설정 (테스트용)
    active: h2

  config:
    import: optional:application-secret.yml
    
  # H2 데이터베이스 설정 (테스트용)
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  mvc:
    async:
      request-timeout: 600000  # SSE 연결 타임아웃 설정 (밀리초)

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${oauth.kakao.client-id}
            client-secret: ${oauth.kakao.client-secret}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - profile_image
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

# swagger
springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
  default-produces-media-type: application/json
  paths-to-match: /**

# Monitoring & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}
      environment: ${spring.profiles.active}

# Custom settings
custom:
  sse:
    timeout: 600000  # SSE 타임아웃 설정 (밀리초, 10분)
