version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ddobang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddobang
      MYSQL_USER: ddobang
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis for Session & Cache
  redis:
    image: redis:7-alpine
    container_name: ddobang-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddobang-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logs:/app/logs

  # Frontend Next.js Server
  frontend:
    build:
      context: ../DDOBANG_FE
      dockerfile: Dockerfile
    container_name: ddobang-frontend
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: ddobang-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend

volumes:
  mysql_data:
  redis_data: