version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: ddobang-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddobang
      MYSQL_USER: ddobang
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  # Redis for Session & Cache
  redis:
    image: redis:7-alpine
    container_name: ddobang-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  # Backend API Server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ddobang-backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    volumes:
      - ./logs:/app/logs

volumes:
  mysql_data:
  redis_data: