global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Spring Boot Backend 메트릭
  - job_name: 'spring-boot-backend'
    static_configs:
      - targets: ['ddobang-backend-1:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  # JMeter 메트릭 (Prometheus Plugin 사용시)
  - job_name: 'jmeter'
    static_configs:
      - targets: ['jmeter:9270']
    scrape_interval: 5s

  # Prometheus 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Grafana 모니터링
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  # MySQL 메트릭은 H2 사용으로 비활성화

# 알림 매니저 설정 (옵션)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093